[phases.setup]
nixPkgs = [
  "python312",
  "glib",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "fontconfig",
  "freetype",
  "harfbuzz",
]
aptPkgs = [
  "shared-mime-info",
  "fonts-liberation",
]

[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[variables]
LD_LIBRARY_PATH = "/root/.nix-profile/lib"
