[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn main:app -c gunicorn.conf.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
